### ISSUE TITLE
 regro-cf-autotick-bot didn't update versions for git_url

### ISSUE THREAD

**Issue by njzjz** [conda-forge/abacus-feedstock#14]
### Comment:

The  regro-cf-autotick-bot never updated versions after #9.
@caic99 we may need to discuss if it is worth using `git_url` without the convenience of the bot.

**Comment by caic99** [comment]
Hi @njzjz ,
Since the submodules in ABACUS are frequently updated, maintaining their version info in the recipe as source files requires additional effort. I think using `git_url` would be better. What's your opinion?

**Comment by njzjz** [comment]
The submodules are not pinned to a specific commit, making it not reproducible. For example, after a submodule gets updated, we may get a different source code when rebuilding, which has the risk of failure.

**Comment by njzjz** [comment]
> You mean using git submodule? They are pinned, instead.

They are updated to the latest during installation: https://github.com/deepmodeling/abacus-develop/blob/e2322fa0983be5f57e48c84a77c3565771aa2037/CMakeLists.txt#L408

**Comment by njzjz** [comment]
libnpy is also dangerous.

**Comment by caic99** [comment]
> > You mean using git submodule? They are pinned, instead.
> 
> They are updated to the latest during installation: https://github.com/deepmodeling/abacus-develop/blob/e2322fa0983be5f57e48c84a77c3565771aa2037/CMakeLists.txt#L408

Yes, and the submodules are updated to the commit indicated here: https://github.com/deepmodeling/abacus-develop/tree/develop/deps . Actually the git submodule infor is also maintained in the .git directory.

**Comment by njzjz** [comment]
> Yes, and the submodules are updated to the commit indicated here: https://github.com/deepmodeling/abacus-develop/tree/develop/deps .

To my knowledge of the [documentation](https://git-scm.com/book/en/v2/Git-Tools-Submodules), `git submodule update` will update the checkout to the latest code in a branch defined in the `.gitsubmdule` file (`master` in abacus) but will not keep the commit.

**Comment by caic99** [comment]
> `git submodule update` will update the checkout to the latest commit in a branch defined in the `.gitsubmdule` file (`master` in abacus) but will not keep the commit.

`git submodule update --remote` does. You can use `git ls-tree HEAD deps/LibRI` to check the pointed commit hash of that submodule.

> --remote
	   This	option is only valid for the update command. Instead of	using
	   the superproject's recorded SHA-1 to	update the submodule, use the
	   status of the submodule's remote-tracking branch.

The `.gitmodules` file is used for `git submodule init`, but not `git submodule update`.
